### PR TITLE
Full screen support

### PR DESCRIPTION
**Pull request by alh45011**
I added a full screen feature. It can be activated by pressing 'F'. Now, there is an issue with snake`s velocity. It moves faster in full screen, but I suggest to fix this in a separate commit.

### CODE REVIEW

**Review by The-Phoenics — CHANGES_REQUESTED** [review]
@alh45011 Please update your branch and push the updated code again as this might lead to a merge conflict.

**Comment by alh45011** [comment]
@Karansemwal sorry I don't fully understand what you've asked me to do. 
git pull command says that "everything is up -to-date"

**Comment by The-Phoenics** [comment]
The changes made in your Pull request have removed the `score` and `game-over` feature which was recently added in #4 @alh45011

**Comment by The-Phoenics** [comment]
Hi @alh45011, I reviewed all of the changes made in your branch. There are a lot of unnecessary changes made. And it is introducing new bugs into the game as you can see in the clip linked below. So for now it cannot be merged into the `main` branch. You can work on this issue on a separate branch so it could be merged later into the main branch when it will be ready.
Also, make sure to keep your branch up to date.

https://www.dropbox.com/s/xxvp7fvyvn4mvcn/2023-05-15%2010-55-20.mkv?dl=0

**Pull request closed without merging**
